### ISSUE TITLE
Callouts all have white background

### ISSUE THREAD

**Issue by Smitty010** [hungsu/typomagical-obsidian#57]
I just tried typomagical today.  I'm running latest obsidian and typomagical (1.1.16/1.5.1).  All of my backgrounds for callouts are now white (I'm running light mode).  They have a border which seems to fade out as you go from right to left.  Is this all by design?  I'd prefer if the callouts had different background colors.

**Comment by hungsu** [comment]
Hi Smitty, yes, this is all by design. There are some other callout styling options if you install the [style settings plugin](https://github.com/mgmeyers/obsidian-style-settings), just set it to Obsidian Default.

![image](https://user-images.githubusercontent.com/1990680/228199642-5bb8b0e0-3abf-46f0-82e3-e0c407c4901f.png)
